### ISSUE TITLE
Does not work in python 2.7-3.4 due to circular dependency

### ISSUE THREAD

**Issue by raghakot** [MultiAgentLearning/playground#37]
when `examples/docker-agent/run.py` is run, it eventually gets to importing `envs.utility` which imports `..characters` which imports `envs.utility` causing circular dependency. 

Circular dependencies are implicitly handled from 3.5+ so it works in 3.6. 
There are two ways of solving this. 

1. Refactor modules to avoid circular dependency
2. Hack fix

Here is the full trace when `examples/docker-agent/run.py` is executed.
```
Traceback (most recent call last):
  File "/home/ragha/playground/examples/docker-agent/run.py", line 3, in <module>
    import pommerman
  File "/home/ragha/playground/pommerman/__init__.py", line 5, in <module>
    from . import configs
  File "/home/ragha/playground/pommerman/configs.py", line 1, in <module>
    from . import envs
  File "/home/ragha/playground/pommerman/envs/__init__.py", line 1, in <module>
    from . import v0
  File "/home/ragha/playground/pommerman/envs/v0.py", line 15, in <module>
    from . import utility
  File "/home/ragha/playground/pommerman/envs/utility.py", line 8, in <module>
    from ..characters import Flame
  File "/home/ragha/playground/pommerman/characters.py", line 5, in <module>
    from .envs import utility
ImportError: cannot import name utility
```

This is the part where circular imports happen.
```
File "/home/ragha/playground/pommerman/envs/v0.py", line 15, in <module>
    from . import utility
  File "/home/ragha/playground/pommerman/envs/utility.py", line 8, in <module>
    from ..characters import Flame
  File "/home/ragha/playground/pommerman/characters.py", line 5, in <module>
    from .envs import utility
```

Ideally, we should refactor to avoid the circular dependency. Which option do we want to go with? Votes?

**Comment by activatedgeek** [comment]
Thanks for pointing it out!

We should avoid circular dependencies. That is the only way.

For now, I'd expect most people to be moving away from Python 2 (so any errors specific to Python 2 won't be a priority)
